### ISSUE TITLE
Increase the default file max

### ISSUE THREAD

**Issue by andrewxhill** [textileio/grpc-ipfs-lite#14]
```
I/System.out: RESOURCE_EXHAUSTED: grpc: received message larger than max (6464397 vs. 4194304)
```

when sending a 5mb file across the api

**Comment by andrewxhill** [comment]
Nevermind. The better thing to do is chunk the file up for sending over the wire. I've done this now in the client and it works great.

**Comment by asutula** [comment]
FWIW, I read a blog post where the guy studied the optimal chunk size for grpc file transfer... 1024 bytes. Do it.

**Comment by andrewxhill** [comment]
oh cool, i just stole the midpoint from this guys "spoiler alert" https://github.com/grpc/grpc.github.io/issues/371 32kb

**Comment by asutula** [comment]
This guys graphs sold me https://ops.tips/blog/sending-files-via-grpc/
